/**
 * Projeções leves da tabela processos — evita select('*') na Fila/Dashboard.
 * O campo `dados` (JSON completo) só deve ir no detalhe do processo.
 */

/** Colunas suficientes para KPI, Fila e cards. */
export const PROCESSOS_LIST_COLUMNS = [
  "id",
  "empresa_id",
  "protocolo_ref",
  "created_by",
  "atendido_por",
  "created_at",
  "updated_at",
  "cliente",
  "cliente_json:dados->>cliente",
  "cliente_upper:dados->>CLIENTE",
  "cliente_title:dados->>Cliente",
  "advogado",
  "escritorio",
  "status",
  "status_interno",
  "observacoes",
  "proximo_retorno",
  "ultimo_retorno",
  "auditado_em",
  "auditado_por",
  "telefone",
  "tribunal",
  "tem_atualizacao_pos_retorno",
  "datajud_encerrado_tribunal",
  "datajud_encerrado_motivo",
  "datajud_ultimo_movimento",
  "datajud_ultimo_nome",
  "datajud_consultado_em",
  "datajud_hash",
  "djen_nova_comunicacao",
  "djen_ultimo_resumo",
  "djen_ultimo_link",
  "djen_ultima_data",
  "indicio_busca_apreensao",
  "busca_apreensao_confianca",
  "busca_apreensao_motivo",
  "busca_apreensao_consultado_em",
  "em_cumprimento_sentenca",
  "cumprimento_sentenca_motivo",
  "cumprimento_sentenca_consultado_em",
  "is_procedente",
  "procedente_motivo",
  "cumprimento_pendente_necessario",
  "status_executivo",
  "detalhes_execucao",
  "data_transito_julgado",
].join(",");

/** Ainda mais leve — só contagens / ranking. */
export const PROCESSOS_KPI_COLUMNS = [
  "id",
  "protocolo_ref",
  "status",
  "datajud_encerrado_tribunal",
  "djen_nova_comunicacao",
  "ultimo_retorno",
  "created_by",
  "atendido_por",
].join(",");
