-- Run manually ONLY on the secondary Supabase project after verifying its project ID.
-- Do not run on the current production database as a migration of existing data.
create table if not exists public.whatsapp_messages (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid null,
  instance_name text null,
  contact_number text not null,
  contact_name text null,
  phone text null,
  remote_jid text null,
  message_id text null,
  message_text text null,
  body text null,
  from_me boolean default false,
  direction text null,
  source text null,
  timestamp timestamptz default now(),
  created_at timestamptz default now(),
  raw_payload jsonb null
);

-- Most reads specify contact_number/phone and order by time.
create index if not exists wa_shard_contact_time on public.whatsapp_messages (contact_number, timestamp desc);
create index if not exists wa_shard_phone_time on public.whatsapp_messages (phone, timestamp desc);
create index if not exists wa_shard_tenant_contact on public.whatsapp_messages (empresa_id, contact_number);
-- Used by trusted server-side service_role only; never expose secondary DB to browser.
alter table public.whatsapp_messages enable row level security;
revoke all on public.whatsapp_messages from anon, authenticated;
grant all on public.whatsapp_messages to service_role;

-- Independent operational telemetry: no process data, passwords or identity records.
-- These tables are intentionally only accessible via trusted server/service-role calls.
create table if not exists public.scan_metrics (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null,
  source text not null,
  success boolean not null,
  error_code text null,
  protocolo_ref text null,
  latency_ms integer null,
  created_at timestamptz not null default now()
);
create index if not exists scan_metrics_tenant_created
  on public.scan_metrics (empresa_id, created_at desc);
create index if not exists scan_metrics_source_created
  on public.scan_metrics (empresa_id, source, created_at desc);
alter table public.scan_metrics enable row level security;
revoke all on public.scan_metrics from anon, authenticated;
grant all on public.scan_metrics to service_role;

create table if not exists public.alert_events (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null,
  protocolo_ref text not null,
  event_type text not null,
  source text null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists alert_events_tenant_created
  on public.alert_events (empresa_id, created_at desc);
create index if not exists alert_events_tenant_protocolo
  on public.alert_events (empresa_id, protocolo_ref, created_at desc);
alter table public.alert_events enable row level security;
revoke all on public.alert_events from anon, authenticated;
grant all on public.alert_events to service_role;
